repos:
-   repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
    -   id: pylint
        args: [--max-line-length=88, --disable=import-error]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-strict-optional, --no-warn-no-return]
