[tool.isort]
profile = "black"

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
no_strict_optional = true
exclude = [
    "venv/",
]

[tool.pylint]
    [tool.pylint.master]
    disable = ["import-error"]
    ignore = ["venv"]
    recursive = ["yes"]
    unsafe-load-any-extension = ["yes"]

    [tool.pylint.'FORMAT']
    max-line-length = 88

    [tool.pylint.'DESIGN']
    max-args = 7
    max-attributes = 8

[tool.pytest.ini_options]
markers = [
    "serial",
]
