name: Python package

on: [push]

jobs:
  build:

    runs-on: windows-2022
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
      - name: Lint with pylint
        run: |
          pylint_runner --max-line-length=88 --disable=import-error --unsafe-load-any-extension=y
      - name: Test with pytest
        run: |
          pytest
